### ISSUE TITLE
Creating nar with boost example

### ISSUE THREAD

**Issue by dant3** [sgeb/gradle-native-artifacts-plugin#1]
Hi,

Didn't found how to ask this question so asking here:
Lets say I have gradle build of C++ app and I want to add boost dependency.
- How to create a boost nar archive?
- How to do it so it works on multiple platforms?

I also thought that it could be great if I could specify needed compiler flags somewhere in dependency, so that just adding it would suffice (i.e. -lboost_something and -Ipath_to_headers would be added for me by plugin). Is this doable?

**Comment by sgeb** [comment]
Hi @dant3 – thanks for your suggestions. I've added a [FAQ section](https://github.com/sgeb/gradle-native-artifacts-plugin#faq) to the plugin's README file. Here are the entries relevant to your questions:
- [How do I create native artifacts from third-party libraries?](https://github.com/sgeb/gradle-native-artifacts-plugin#how-do-i-create-native-artifacts-from-third-party-libraries)
- [How do I cross-compile to different platforms?](https://github.com/sgeb/gradle-native-artifacts-plugin#how-do-i-cross-compile-to-different-platforms)
- [Are there any examples or real-life projects using this plugin?](https://github.com/sgeb/gradle-native-artifacts-plugin#are-there-any-examples-or-real-life-projects-using-this-plugin)

Regarding your last point: specifying compiler/linker flags inside the native artifact is definitely an interesting feature and has been on my list for a future release. See [this FAQ entry](https://github.com/sgeb/gradle-native-artifacts-plugin#can-additional-compilerlinker-flags-be-specified-in-a-native-artifact) and #2.

If you use this plugin on an open-source project let me know the URL and I will include it in the FAQ as an example for other users.

Hope this covers your questions. Feel free to re-open this issue if you need more input.
